### ISSUE TITLE
version compatibility update

### ISSUE THREAD

**Issue by leleu** [playandbuild/scrapy-history-middleware#2]
Hi Joel,

I'm really interested in your history-middleware package for scrapy, particularly the ability to use s3 as a cache.

Unfortunately, it seems like parsedatetime and scrapy have updated their APIs and broken backwards compat.  I fixed the parsedatetime issue by changing line 2 in middleware.py as follows:

`from parsedatetime import parsedatetime, parsedatetime_consts`
to
`from parsedatetime import parsedatetime, Constants as parsedatetime_consts`

(I'd do a pull request, but I don't know how... Sorry!)

The other issue that I cannot figure out is that history middleware cannot import a necessary module correctly. I believe this is due to scrapy changing their API.  The error I see in my stdout is:

`ImportError: Error loading object 'mycrawler.history.middleware.HistoryMiddleware': cannot import name crawler`

I was wondering if you can help me get this issue resolved.

Thanks,
Travis

**Comment by wvengen** [comment]
I'm having the same problem `cannot import name crawler`, no clue yet.

**Comment by wvengen** [comment]
Ok, the import error comes from `scrapy.stats` trying to import `crawler` from `project`, which somehow isn't available (try running `import scrapy.stats` from `ipython`).

Workaround: move `from scrapy.stats import stats` into `#process_response` ...

**Comment by arhpreston** [comment]
Strange. It could be that newer versions of scrapy do things differently. Thanks for posting the workaround.

**Comment by wvengen** [comment]
I guess so. The other thing I needed to change was editing `from scrapy.core.downloader.responsetypes import responsetypes` to `from scrapy.responsetypes import responsetypes`. If you're interested, I could make a pull request when all is running smoothly in my setup.

**Comment by arhpreston** [comment]
:+1: please do.
